# Generated by Django 4.2.11 on 2025-03-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_commun', models.CharField(max_length=100)),
                ('nom_scientifique', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('saison_culture', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type_de_sol', models.CharField(blank=True, max_length=100, null=True)),
                ('climat', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('periode_utilisation', models.CharField(blank=True, max_length=100, null=True)),
                ('plante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='api.plantes')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='api.zones')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.CharField(max_length=200)),
                ('resultat', models.CharField(max_length=100)),
                ('conseils', models.TextField(blank=True, null=True)),
                ('plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='api.plantes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='api.users')),
            ],
        ),
    ]
