# Generated by Django 5.1.6 on 2025-03-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('periode_utilisation', models.CharField(blank=True, max_length=100, null=True)),
                ('plante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommandations', to='api.plantes')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommandations', to='api.zones')),
            ],
        ),
        migrations.DeleteModel(
            name='Recommendations',
        ),
    ]
